### PR TITLE
Update packages to fix vulnerabilities reported by npm audit

### PR DESCRIPTION
**Pull request by Hypnosphi**
Required for fixing https://github.com/gemini-testing/hermione/issues/456 https://github.com/gemini-testing/hermione/issues/359

### CODE REVIEW

**Comment by Hypnosphi** [comment]
@DudaGod @sipayRT can you please review?

**Comment by DudaGod** [comment]
Hello. Before merge it I should run our integration tests in conjunction with hermione. I will try to do it today.

**Comment by DudaGod** [comment]
Update of uglifyify fail all tests with error - ``sourcemap` is not a supported option while parsing file: /place/sandbox-data/ramdrive/668884206/tmp/tmpdWFO1S/node_modules/hermione/node_modules/gemini-core/lib/browser/client-scripts/index.js`.

I suggest to remove it from current update because as far as I remember new versions of uglifyify do not support the old internet explorer.

**Comment by Hypnosphi** [comment]
unfortunately, earlier versions of `uglifyify` depend on `extend@^1.2.1` which is vulnerable according to https://www.npmjs.com/advisories/996. One possible solution is to use `uglify-es` directly

**Comment by DudaGod** [comment]
I suggest update now only `lodash`, `png-img` and `mocha`. This will allow us to get rid of some vulnerabilities. And then explore the possibility of change `uglifyify` to something else.

**Comment by DudaGod** [comment]
Thank you, release in gemini-core@5.1.1.

**Pull request merged**
