### PR TITLE
#43 Add TS support

### PR DESCRIPTION
**Pull request by Tocher**
#43 add .ts extension

### CODE REVIEW

**Comment by Tocher** [comment]
@sipayRT hi, can you review this PR?

**Comment by sigorilla** [comment]
@sipayRT ping

**Comment by sipayRT** [comment]
@sigorilla hi
we already discussed with @Tocher another solution. It should be option to set formats for tests

**Comment by sigorilla** [comment]
Where can we check the  status of this solution?

**Comment by sipayRT** [comment]
https://nda.ya.ru/3Vpsdb

**Comment by personaljs** [comment]
Костя, привет. Давай доведем до конца этот пулл-реквест?

**Comment by Tocher** [comment]
https://github.com/gemini-testing/gemini-core/pull/72

**Pull request closed without merging**
